PennController.ResetPrefix(null); // Shorten command names (keep this line here)

// Disable debug
PennController.DebugOff();

// var counterOverride = 5;

// Do show progress bar
var showProgressBar = true;

var shuffleSequence = seq(
  'consent',
  'practice1',
  'practice2',
  'practice3',
  'shared-intro',
  sepWith("timeoutSep", rshuffle(startsWith("ILOSTMYMARBLES"), startsWith("RIPPERONI"), startswith("MOZZARELLA"))),
  'debrief'
);

function blank(a, b) {
   var sentence = b ? b : a;
   var n = b ? a : null;

   var seq = [""];
   var inBlank = false;
   for (var i = 0; i < sentence.length; ++i) {
       var c = sentence.charAt(i)
       if (inBlank) {
           if (c == '_')
               (seq[seq.length-1])++;
           else {
               seq.push(c);
               inBlank = true;
           }
       }
       else {
           if (c != '_')
               seq[seq.length-1] += c
           else {
               seq.push(1);
               inBlank = true;
           }
       }
   }

   var ihtml = "";
   var bcount = 0;
   for (var i = 0; i < seq.length; ++i) {
       if (typeof(seq[i]) == "number") {
           ++bcount;
           var input = " <input type='text' name='blank-" + bcount + "' size='" + (n ? n : seq[i]) + "'></input> ";
           ihtml += input;
       }
       else {
           ihtml += $("<div>").text(seq[i])[0].innerHTML;
       }
   }

   var e = "<p>";
   var validators = { };
   var bcount = 0;
   for (var i = 0; i < seq.length; ++i) {
       if (typeof(seq[i]) == "number") {
           ++bcount;
           e += "<label class='error' for='blank-" + bcount + "'></label>";
           validators['blank-' + bcount] = function (s) { if (s && ! s.match(/^\s*$/)) return true; else return "You must fill in the blank."; }
       }
   }
   e += "</p>"

   return {
       html: "<p>" + ihtml + "</p>" + e,
       validators: validators
   };
}


// Using modified controller coded by Ethan Poole (Umass, 2017)
// Disallows use of mouse for responses.
var DS = 'EPDashedSentence';

//  Set the Prolific Academic Completion URL
var sendingResultsMessage = "Please wait. Your data is being sent to the server.";
var completionMessage = "Thank you for your participation! Your responses have been stored, and you are free to close out of the experiment.";
var completionErrorMessage = "There was an error in sending your data to the server. You may still complete this experiment, but you may have to go through it again.";

// Controller settings.
var defaults = [
  "Question", {
    hasCorrect: true,
    presentHorizontally: false
  },
  "EPDashedSentence", {
    mode: "self-paced reading",
    display: "in place"
  }
];

// Items array.
var items = [

  ["consent", "Form", { consentRequired: true, html: { include: "consent.html" } }],
  ["intro", "Form", { consentRequired: true, html: { include: "intro.html" } }],
  ["debrief", "Form", { consentRequired: true, html: { include: "debrief.html" } }],

  ['shared-intro', "Form", { consentRequired: false, html: { include: "practice1.html" } }],
  ['shared-intro', "Form", { consentRequired: false, html: { include: "practice2.html" } }],
  ['shared-intro', "Form", { consentRequired: false, html: { include: "practice3.html" } }],


  ['shared-intro', Separator, { transfer: 1000, normalMessage: "", errorMessage: "Wrong answer. Please read slowly and carefully." }, DS, { s: "This sentence is to get you used to the reading style." }],
  ['shared-intro', Separator, { transfer: 1000, normalMessage: "", errorMessage: "Wrong answer. Please read slowly and carefully." }, DS, { s: "This is another sentence, which is a bit more complicated than the one that came before it." }],

  ['shared-intro', Message, {
    consentRequired: false,
    html: ["div",
      ["p", "How was that? It is important that you move through the sentence carefully and deliberately, making sure that you understand each word as you go."],
      ["p", "Let's try some more."]
    ]
  }],

  ['shared-intro', Separator, { transfer: 1000, normalMessage: "", errorMessage: "Not the answer we were expecting. Be sure to read carefully." }, DS, { s: "At the ball, the prince waltzed and slowly smiled at the princess." }, Question, { q: "On the prince's face was a ___.", as: ["smile", "grimace"] }],
  ['shared-intro', Separator, { transfer: 1000, normalMessage: "", errorMessage: "Not the answer we were expecting. Be sure to read carefully." }, DS, { s: "Without warning, Geoffrey turned and screamed at the waiter who had embarrassed him." }, Question, { q: "The waiter ___.", as: ["embarrassed Geoffrey", "felt embarrassed by Geoffrey"] }],
  ['shared-intro', Separator, { transfer: 1000, normalMessage: "", errorMessage: "Not the answer we were expecting. Be sure to read carefully." }, DS, { s: "The trainee talking to the barista lazily made a latte and didn't even try to make a design on top." }, Question, { q: "The trainee was probably ___.", as: ["not very attentive", "following procedure"] }],
  ['shared-intro', Separator, { transfer: 1000, normalMessage: "", errorMessage: "Not the answer we were expecting. Be sure to read carefully." }, DS, { s: "Madame de Plessy sat up all night worrying about her son who was on the front lines." }, Question, { q: "Madame de Plessy was concerned about ___.", as: ["her son", "her husband"] }],

  ['shared-intro', Message, {
    consentRequired: false,
    html: ["div",
      ["p", "Alright, that's it for practice! If you got any wrong, that's OK. Just be sure to read naturally but carefully, making sure you understand each word as you go. Press any key when you're ready to begin."]
    ]
  }],

  ['shared-intro', "Separator", { transfer: 4000, normalMessage: "Hands in place! Your first sentence of this block will start soon." }],

  ["timeoutSep", Separator, { transfer: 1000, normalMessage: "", errorMessage: "Not the answer we were expecting. Be sure to read carefully." }],

//// Shared experimental items + fillers
//// Itemsets group ILOSTMYMARBLES  
[["ILOSTMYMARBLES-a",1], DS, {s:"James spilled the beans in the kitchen after preparing his friends for the event."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-b",1], DS, {s:"James spilled the beans in the kitchen after preparing his food for the event."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-c",1], DS, {s:"James spilled the soup in the kitchen after preparing his friends for the event."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-d",1], DS, {s:"James spilled the soup in the kitchen after preparing his food for the event."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-a",2], DS, {s:"Josie kicked the bucket on Wednesday during an accident involving a bulldozer."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-b",2], DS, {s:"Josie kicked the bucket on Wednesday during an argument involving a bulldozer."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-c",2], DS, {s:"Josie kicked the pylon on Wednesday during an accident involving a bulldozer."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-d",2], DS, {s:"Josie kicked the pylon on Wednesday during an argument involving a bulldozer."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-a",3], DS, {s:"Tom bit the bullet before firing an ineffective employee at the shooting range."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-b",3], DS, {s:"Tom bit the bullet before firing an ineffective gun at the shooting range."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-c",3], DS, {s:"Tom bit his lip before firing an ineffective employee at the shooting range."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-d",3], DS, {s:"Tom bit his lip before firing an ineffective gun at the shooting range."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-a",4], DS, {s:"Mary let the cat out of the bag at the veterinarian's office in order to get the appointment started."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-b",4], DS, {s:"Mary let the cat out of the bag at the veterinarian’s office in order to get the conversation started."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-c",4], DS, {s:"Mary let the dog out of the bag at the veterinarian's office in order to get the appointment started."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-d",4], DS, {s:"Mary let the dog out of the bag at the veterinarian’s office in order to get the conversation started."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-a",5], DS, {s:"Mark threw Jack under the bus in the parking lot after getting caught by the parents association at the school."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-b",5], DS, {s:"Mark threw Jack under the bus in the parking lot after getting caught by the security cameras at the school."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-c",5], DS, {s:"Mark threw Jack under the truck in the parking lot after getting caught by the parents association at the school."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-d",5], DS, {s:"Mark threw Jack under the truck in the parking lot after getting caught by the security cameras at the school."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-a",6], DS, {s:"Peter burned a bridge with Kate because of their newfound disdain for one another."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-b",6], DS, {s:"Peter burned a bridge with Kate because of their newfound disdain for the law."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-c",6], DS, {s:"Peter burned a shrub with Kate because of their newfound disdain for one another."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-d",6], DS, {s:"Peter burned a shrub with Kate because of their newfound disdain for the law."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-a",7], DS, {s:"Tina hit the hay after a long day of hard work in order to prepare for the next day’s shift."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-b",7], DS, {s:"Tina hit the hay after a long day of hard work in order to prepare for the next day’s processing."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-c",7], DS, {s:"Tina hit the ledger after a long day of hard work in order to prepare for the next day’s shift."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-d",7], DS, {s:"Tina hit the ledger after a long day of hard work in order to prepare for the next day’s processing."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-a",8], DS, {s:"Andrew went the extra mile to make his track coach happy after a disappointing day."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-b",8], DS, {s:"Andrew went the extra mile to make his sister happy after a disappointing day."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-c",8], DS, {s:"Andrew ran the extra mile to make his track coach happy after a disappointing day."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-d",8], DS, {s:"Andrew ran the extra mile to make his sister happy after a disappointing day."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-a",9], DS, {s:"Amanda didn't buy Luke's explanation since he had proven himself untrustworthy."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-b",9], DS, {s:"Amanda didn't buy Luke's encyclopedia since he had proven himself untrustworthy."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-c",9], DS, {s:"Amanda didn't want Luke's explanation since he had proven himself untrustworthy."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-d",9], DS, {s:"Amanda didn't want Luke's encyclopedia since he had proven himself untrustworthy."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-a",10], DS, {s:"Mazie broke the bank on Monday after using her credit card too much while going on a bender."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-b",10], DS, {s:"Mazie broke the bank on Monday after using her crowbar too much while going on a bender."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-c",10], DS, {s:"Mazie broke the machine after using her credit card too much while going on a bender."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-d",10], DS, {s:"Mazie broke the machine after using her crowbar too much while going on a bender."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-a",11], DS, {s:"Lily played it by ear with regards to executing the plan in order to finish the film by the deadline."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-b",11], DS, {s:"Lily played it by ear with regards to executing the score in order to finish the film by the deadline."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-c",11], DS, {s:"Lily played it by memory with regards to executing the plan in order to finish the film by the deadline."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-d",11], DS, {s:"Lily played it by memory with regards to executing the score in order to finish the film by the deadline."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-a",12], DS, {s:"Janet woke up on the wrong side of the bed on Friday after forgetting her alarm."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-b",12], DS, {s:"Janet woke up on the wrong side of the bed on Friday after forgetting her directions."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-c",12], DS, {s:"Janet woke up on the wrong side of the hammock on Friday after forgetting her alarm."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-d",12], DS, {s:"Janet woke up on the wrong side of the hammock on Friday after forgetting her directions."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-a",13], DS, {s:"Emma tried to break the ice by telling a joke during the meeting."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-b",13], DS, {s:"Emma tried to break the ice by using a hammer during the meeting."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-c",13], DS, {s:"Emma tried to break the CEO by telling a joke during the meeting."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["ILOSTMYMARBLES-d",13], DS, {s:"Emma tried to break the CEO by using a hammer during the meeting."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],

  //// Fillers group RIPPERONI
[["RIPPERONI-a",14], DS, {s:"The students were packed like sardines into the bus for their field trip."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-b",14], DS, {s:"The bar was so full that its patrons were packed like sardines into the space."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-c",14], DS, {s:"Josie retreated into her room to blow off steam after an exhausting day."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-d",14], DS, {s:"Shortly after a heated argument Chris screamed into a pillow to blow off steam."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-e",14], DS, {s:"After incurring a fourth infraction Tim knew he was on thin ice with his boss."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-f",14], DS, {s:"Nina knew she was on thin ice but couldn't resist taunting Matthias."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-g",14], DS, {s:"Hunter woke up feeling under the weather and didn't go grocery shopping."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-h",14], DS, {s:"Siobhan missed the card game because she was under the weather."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-a",15], DS, {s:"Nobody could ignore the elephant in the room as the deadline approached."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-b",15], DS, {s:"The description of the video rang a bell although Kayla couldn't remember where she'd seen it."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-c",15], DS, {s:"Hearing about the Mongols rang a bell from one of Joe's history classes."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-d",15], DS, {s:"Allison went on a wild goose chase to find and photograph a phoenix."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-e",15], DS, {s:"Alice's brother sent her on a wild goose chase to get him a book that didn't exist."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-f",15], DS, {s:"Bob and Sally knew it was time to face the music when their manager called."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-g",15], DS, {s:"The condemned woman finally faced the music as she stood before the gallows."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-h",15], DS, {s:"Spencer thought it was a piece of cake to finish the task efficiently."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-a",16], DS, {s:"The chorus was a piece of cake for Mei to write."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-b",16], DS, {s:"Alex had a bone to pick with the girl who yelled at him last Sunday."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-c",16], DS, {s:"After Emily ruined his plans Brennan had a bone to pick with her."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-d",16], DS, {s:"Miles told Jenny to break a leg before her debut in a stage production. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-e",16], DS, {s:"The students were told to break a leg by the production assisstant. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-f",16], DS, {s:"Millie was unhappy in her relationship and Joel was only fanning the flames. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-g",16], DS, {s:"Jess fanned the flames of the argument by bringing up politics at dinner. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-h",16], DS, {s:"Noah was on the fence about buying a new electric vehicle. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-a",17], DS, {s:"Richard would have asked Doug to go out for dinner but he was on the fence about it. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-b",17], DS, {s:"In order to make the project deadline Lexi was going to have to start cutting corners. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-c",17], DS, {s:"The company begain to cut corners in order to recoup their losses. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-d",17], DS, {s:"Spencer thought Elsie committed the act but it turns out he was barking up the wrong tree. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-e",17], DS, {s:"Lucas threw caution to the wind when he decided to move to Germany. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-f",17], DS, {s:"Alice was known to throw caution to the wind when it came to sports. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-g",17], DS, {s:"Mitchell jumped the gun and submitted his essay before it was ready. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["RIPPERONI-h",17], DS, {s:"The students lost their marbles after wracking their brains to finish the complicated project."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],

  //// Fillers group MOZZARELLA
[["MOZZARELLA-a",24], DS, {s:"Luke could not hear the sound of his own voice over the loud music in the club. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-b",24], DS, {s:"Levi refused to sit down at the table in order to make room for an elderly woman. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-c",24], DS, {s:"The seagull stole a french fry from the bewildered toddler who cried afterwards. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-d",24], DS, {s:"Harvey was a fan of sports but did not enjoy attending live games. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-e",24], DS, {s:"Hank thought he heard something in the woods after putting the campfire out."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-f",24], DS, {s:"The scuba diver was having trouble managing their equipment.  "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-g",24], DS, {s:"The horses ran free on the ranch after being taken out of the barn. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-h",24], DS, {s:"Jenna had to take a detour after finding out the road ahead was closed for repairs. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-a",25], DS, {s:"The machinist repaired the drill after it had suffered a breakdown. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-b",25], DS, {s:"The bartender put out the last call for drinks as it was nearing the establishment's closing. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-c",25], DS, {s:"Skylar was known to be clumsy as he fell down often. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-d",25], DS, {s:"Gus was very pessimistic and did not hold high hopes for the future. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-e",25], DS, {s:"Cheryl asked for directions as being hopelessly lost was not fun. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-f",25], DS, {s:"Tracy watered her potted plants lovingly as the sun shined on. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-g",25], DS, {s:"The pilot preferred flying on a sunny day than on a rainy one. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-h",25], DS, {s:"Hal was wide awake when the earthquake hit the town and a building collapsed."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-a",26], DS, {s:"Cole was not finished with his exam by the time the fire alarm went off. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-b",26], DS, {s:"Chris could not sleep unless white noise was playing in the background. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-c",26], DS, {s:"Lettie was completely prepared for the day and it showed. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-d",26], DS, {s:"Harrison wondered if life had any meaning and expected no answer. "},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-e",26], DS, {s:"Cherry blossoms swirled into the room through the open window."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-f",26], DS, {s:"Kit helped her friend prepare a pot for growing flowers."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-g",26], DS, {s:"The morose student sat on the bench and silently watched the ocean."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")],
[["MOZZARELLA-h",26], DS, {s:"Alexis smiled as she watched her cat stretching in a sunbeam."},"Form",blank("Rephrase what you just read. ____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________")];